/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 sneaker.gltf --transform 
Files: sneaker.gltf [17.04MB] > sneaker-transformed.glb [6.12MB] (64%)
Author: Arsutoria - The Workshop School (https://sketchfab.com/arsutoriaschool)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/sneaker-3d-model-d705aa12396f44738880e28a694d8a00
Title: Sneaker 3D model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/sneaker-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['0_Material_1_0'].geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh geometry={nodes['Object_2_Plaster_(3)_0'].geometry} material={materials.PaletteMaterial002} scale={0.001} />
      <mesh geometry={nodes.Object_12_Blue_felt_0.geometry} material={materials.Blue_felt} scale={0.001} />
      <mesh geometry={nodes.Object_26_Leather_light_brown_0.geometry} material={materials.Leather_light_brown} scale={0.001} />
      <mesh geometry={nodes['Object_29_Metal_(3)_0'].geometry} material={materials.PaletteMaterial003} scale={0.001} />
      <mesh geometry={nodes.Object_131_Japanese_texture_fabric_0.geometry} material={materials.Japanese_texture_fabric} scale={0.001} />
      <mesh geometry={nodes.Object_20_Denim_dark_blue_0.geometry} material={materials.Denim_dark_blue} scale={0.001} />
      <mesh geometry={nodes['Object_110_Metal_(1)_0'].geometry} material={materials.PaletteMaterial004} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/sneaker-transformed.glb')
