/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 air.gltf --transform 
Files: air.gltf [974.14KB] > air-transformed.glb [114.9KB] (88%)
Author: iSteven (https://sketchfab.com/OneSteven)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/ipad-air-2023-af98985bdeb84b159d8a51216157f390
Title: iPad Air 2023
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/air-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material} rotation={[-1.633, 0.191, 0.314]} />
    </group>
  )
}

useGLTF.preload('/air-transformed.glb')
