/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 app.gltf --transform 
Files: app.gltf [7.81MB] > app-transformed.glb [719KB] (91%)
Author: nickheitzman (https://sketchfab.com/nickheitzman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/app-island-2d22e05e4049493c9f47de897bb67c5e
Title: App Island
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
	const { nodes, materials } = useGLTF('/app-transformed.glb')
	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.pCube1_Phone_Back_Stuff_0.geometry} material={materials.Phone_Back_Stuff} scale={0.01} />
			<mesh geometry={nodes.pCube1_Gray_Metals_0.geometry} material={materials.Gray_Metals} scale={0.01} />
			<mesh geometry={nodes.pCylinder1_Sandy_0.geometry} material={materials.Sandy} scale={0.01} />
			<mesh geometry={nodes.pPlane1_Water_0.geometry} material={materials.Water} scale={0.01} />
			<mesh geometry={nodes.pCylinder2_Tree_Trunk_0.geometry} material={materials.Tree_Trunk} position={[0.007, -0.002, -0.003]} scale={0.01} />
			<mesh geometry={nodes.pSphere1_Coconut_0.geometry} material={materials.Coconut} position={[0.024, -0.003, -0.002]} rotation={[0, 0, Math.PI / 6]} scale={0.01} />
			<mesh geometry={nodes.pPlane7_Frond_0.geometry} material={materials.Frond} position={[0, 0.004, 0.005]} rotation={[-0.253, 0.067, -0.253]} scale={0.01} />
			<mesh geometry={nodes.pCube3_Wood_Parts_0.geometry} material={materials.Wood_Parts} position={[0, -0.003, 0]} scale={0.013} />
			<mesh geometry={nodes.pCylinder8_Light_Metal_0.geometry} material={materials.Light_Metal} position={[0, -0.003, 0]} scale={0.013} />
			<mesh geometry={nodes.pCylinder15_Chairs_0.geometry} material={materials.Chairs} position={[0, -0.003, 0]} scale={0.013} />
			<mesh geometry={nodes.pCube8_Icon1_0.geometry} material={materials.Icon1} position={[0, 0.002, 0]} rotation={[-0.068, 0, 0]} scale={0.01} />
			<mesh geometry={nodes.pCube13_Icon9_0.geometry} material={materials.Icon9} position={[-0.007, -0.001, 0]} rotation={[0.067, 0.523, -0.033]} scale={0.01} />
			<mesh geometry={nodes.pCube23_Icon8_0.geometry} material={materials.Icon8} position={[-0.017, 0, -0.02]} rotation={[0, 0, -0.064]} scale={0.01} />
			<mesh geometry={nodes.pCube24_Icon7_0.geometry} material={materials.Icon7} position={[0.017, -0.001, -0.02]} rotation={[0.055, 0, 0.032]} scale={0.01} />
			<mesh geometry={nodes.pCube25_Icon5_0.geometry} material={materials.Icon5} position={[0.026, 0, -0.005]} rotation={[0, 0.262, 0]} scale={0.01} />
			<mesh geometry={nodes.pCube26_Icon4_0.geometry} material={materials.Icon4} position={[0, -0.005, -0.021]} rotation={[0.204, 0, -0.191]} scale={0.01} />
			<mesh geometry={nodes.pCube29_Icon6_0.geometry} material={materials.Icon6} position={[-0.018, 0, 0.065]} rotation={[0, 0, 0.042]} scale={0.01} />
			<mesh geometry={nodes.pCube30_Icon2_0.geometry} material={materials.Icon2} position={[0.008, -0.002, 0.041]} rotation={[0.087, -0.522, 0.044]} scale={0.01} />
			<mesh geometry={nodes.pCube68_Icon3_0.geometry} material={materials.Icon3} position={[-0.033, -0.005, 0.026]} rotation={[0.779, -1.226, 0.694]} scale={0.01} />
			<mesh geometry={nodes.pCube69_Icon11_0.geometry} material={materials.Icon11} position={[0.018, -0.001, 0.065]} rotation={[0, 0, -0.146]} scale={0.01} />
			<mesh geometry={nodes.pCylinder16_Floaty_Details_0.geometry} material={materials.Floaty_Details} position={[-0.001, 0, 0]} rotation={[0, Math.PI / 4, 0]} scale={0.01} />
			<mesh geometry={nodes.pPlane10_Water_Walk_0.geometry} material={materials.Water_Walk} scale={0.01} />
			<mesh geometry={nodes.pCylinder18_lambert1_0.geometry} material={materials.lambert1} position={[0.002, 0.003, 0.006]} rotation={[-0.04, 0.148, 0.264]} scale={0.011} />
			<mesh geometry={nodes.pCylinder18_Medium_Metal_0.geometry} material={materials.Medium_Metal} position={[0.002, 0.003, 0.006]} rotation={[-0.04, 0.148, 0.264]} scale={0.011} />
			<mesh geometry={nodes.pPlane19_Umbrella_Yellow_0.geometry} material={materials.Umbrella_Yellow} position={[0.002, 0.003, 0.006]} rotation={[-0.04, 0.148, 0.264]} scale={0.011} />
			<mesh geometry={nodes.polySurface1_Icon10_0.geometry} material={materials.Icon10} position={[-0.027, -0.003, -0.033]} rotation={[0, -0.262, 0]} scale={0.01} />
			<instancedMesh args={[nodes.pSphere7_Light_Metal_0.geometry, materials.Light_Metal, 26]} instanceMatrix={nodes.pSphere7_Light_Metal_0.instanceMatrix} />
		</group>
	)
}

useGLTF.preload('/app-transformed.glb')
