/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ok.gltf --transform 
Files: ok.gltf [182.61KB] > ok-transformed.glb [160.11KB] (12%)
Author: gutterfunk (https://sketchfab.com/gutterfunk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hand-ok-a2b57aa35e9f4b11b3568e662a0e20bd
Title: Hand OK
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
	const { nodes, materials } = useGLTF('/ok-transformed.glb')
	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} />
		</group>
	)
}

useGLTF.preload('/ok-transformed.glb')
