/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 SupportService.gltf --transform 
Files: SupportService.gltf [536.2KB] > SupportService-transformed.glb [447.28KB] (17%)
Author: Without texture 3d (https://sketchfab.com/without_texture)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/handshake-ramadhan-series-a784711be28440a1b0251cc21d904202
Title: Handshake - Ramadhan Series
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
	const { nodes, materials } = useGLTF('/SupportService-transformed.glb')
	return (
		<group {...props} dispose={null}>
			<primitive object={nodes.GLTF_created_0_rootJoint} />
			<primitive object={nodes.GLTF_created_1_rootJoint} />
			<skinnedMesh geometry={nodes.Object_7.geometry} material={materials['Material.011']} skeleton={nodes.Object_7.skeleton} position={[1.016, -1.389, 0.776]} rotation={[-0.429, 0, 0]} />
			<skinnedMesh geometry={nodes.Object_34.geometry} material={materials['Material.004']} skeleton={nodes.Object_34.skeleton} position={[-1.712, -1.365, 0.665]} rotation={[-2.713, 0, -Math.PI]} />
		</group>
	)
}

useGLTF.preload('/SupportService-transformed.glb')
